Entity/Post.php
<?php

/*
 * This file is part of the CCDNForum ForumBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNForum\ForumBundle\Entity;

use CCDNForum\ForumBundle\Entity\Model\Post as AbstractPost;

/**
 *
 * @category CCDNForum
 * @package  ForumBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNForumForumBundle
 *
 */
class Post extends AbstractPost
{
    /**
     *
     * @var integer $id
     */
    protected $id;

    /**
     *
     * @var string $body
     */
    protected $body;

    /**
     *
     * @var \DateTime $createdDate
     */
    protected $createdDate;

    /**
     *
     * @var \DateTime $editedDate
     */
    protected $editedDate;

    /**
     *
     * @var Boolean $isDeleted
     */
    protected $isDeleted = false;

    /**
     *
     * @var \DateTime $deletedDate
     */
    protected $deletedDate;

    /**
     *
     * @var \DateTime $unlockedDate
     */
    protected $unlockedDate;

    /**
     *
     * @var \DateTime $unlockedUntilDate
     */
    protected $unlockedUntilDate;

    /**
     *
     * @access public
     */
    public function __construct()
    {
        parent::__construct();
        // your own logic

        $this->unlockedDate = new \Datetime('now');
        $this->unlockedUntilDate = new \Datetime('now + 7 days');
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Set body
     *
     * @param  string $body
     * @return Post
     */
    public function setBody($body)
    {
        $this->body = $body;

        return $this;
    }

    /**
     * Get createdDate
     *
     * @return \datetime
     */
    public function getCreatedDate()
    {
        return $this->createdDate;
    }

    /**
     * Set createdDate
     *
     * @param  \datetime $createdDate
     * @return Post
     */
    public function setCreatedDate($createdDate)
    {
        $this->createdDate = $createdDate;

        return $this;
    }

    /**
     * Get edited_date
     *
     * @return \datetime
     */
    public function getEditedDate()
    {
        return $this->editedDate;
    }

    /**
     * Set editedDate
     *
     * @param  \datetime $editedDate
     * @return Post
     */
    public function setEditedDate($editedDate)
    {
        $this->editedDate = $editedDate;

        return $this;
    }

    /**
     * Get isDeleted
     *
     * @return boolean
     */
    public function isDeleted()
    {
        return $this->isDeleted;
    }

    /**
     * Set is_deleted
     *
     * @param  boolean $isDeleted
     * @return Post
     */
    public function setDeleted($isDeleted)
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    /**
     * Get deletedDate
     *
     * @return \datetime
     */
    public function getDeletedDate()
    {
        return $this->deletedDate;
    }

    /**
     * Set deletedDate
     *
     * @param  \datetime $deletedDate
     * @return Post
     */
    public function setDeletedDate($deletedDate)
    {
        $this->deletedDate = $deletedDate;

        return $this;
    }

    /**
     * Get unlockedDate
     *
     * @return \datetime
     */
    public function getUnlockedDate()
    {
        return $this->unlockedDate;
    }

    /**
     * Set unlockedDate
     *
     * @param  \datetime $datetime
     * @return Post
     */
    public function setUnlockedDate(\Datetime $datetime)
    {
        $this->unlockedDate = $datetime;

        return $this;
    }

    /**
     * Get unlockedUntilDate
     *
     * @return \datetime
     */
    public function getUnlockedUntilDate()
    {
        return $this->unlockedUntilDate;
    }

    /**
     * Set unlockedUntilDate
     *
     * @param  \datetime $datetime
     * @return Post
     */
    public function setUnlockedUntilDate(\Datetime $datetime)
    {
        $this->unlockedUntilDate = $datetime;

        return $this;
    }

    /**
     * Get isUnlocked
     *
     * @return \datetime
     */
    public function isLocked()
    {
        return $this->unlockedUntilDate > new \Datetime('now') ? false : true;
    }
}

Form/Type/Moderator/Post/PostUnlockFormType.php
<?php

/*
 * This file is part of the CCDNForum ForumBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNForum\ForumBundle\Form\Type\Moderator\Post;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 *
 * @category CCDNForum
 * @package  ForumBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNForumForumBundle
 *
 */
class PostUnlockFormType extends AbstractType
{
    /**
     *
     * @access protected
     * @var string $postClass
     */
    protected $postClass;

    /**
     *
     * @access public
     * @param string $postClass
     */
    public function __construct($postClass)
    {
        $this->postClass = $postClass;
    }

    /**
     *
     * @access public
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('unlockedUntilDate', 'date',
                array(
                    'mapped'             => true,
                    'required'           => true,
                    'label'              => 'post.unlock-until-label',
                    'translation_domain' => 'CCDNForumForumBundle',
                    'data'               => new \Datetime('today + 1 day')
                )
            )
        ;
    }

    /**
     *
     * @access public
     * @param \Symfony\Component\OptionsResolver\OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class'          => $this->postClass,
            'csrf_protection'     => true,
            'csrf_field_name'     => '_token',
            // a unique key to help generate the secret token
            'intention'           => 'forum_post_unlock_item',
            'validation_groups'   => array('forum_post_unlock'),
            'cascade_validation'  => true,
        ));
    }

    /**
     *
     * @access public
     * @return string
     */
    public function getName()
    {
        return 'Post';
    }
}

Controller/PostController.php
<?php

/*
 * This file is part of the CCDNForum ForumBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNForum\ForumBundle\Controller;

use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 *
 * @category CCDNForum
 * @package  ForumBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNForumForumBundle
 *
 */
class PostController extends PostBaseController
{
    /**
     *
     * @access public
     * @param  int            $postId
     * @return RenderResponse
     */
    public function showAction($postId)
    {
        // Get post by id.
        $post = $this->getPostModel()->findOneByIdWithTopicAndBoard($postId);
        $this->isFound($post);
        $this->isAuthorisedToViewPost($post);

        // Get the topic subscriptions.
        $subscription = $this->getSubscriptionModel()->findSubscriptionForTopicById($post->getTopic()->getId());
        $subscriberCount = $this->getSubscriptionModel()->countSubscriptionsForTopicById($post->getTopic()->getId());

        // Setup crumb trail.
        $topic = $post->getTopic();
        $board = $topic->getBoard();
        $category = $board->getCategory();

        $crumbs = $this->getCrumbs()
            ->add($this->trans('crumbs.category.index'), $this->path('ccdn_forum_forum_category_index'))
            ->add($category->getName(), $this->path('ccdn_forum_forum_category_show', array('categoryId' => $category->getId())))
            ->add($board->getName(), $this->path('ccdn_forum_forum_board_show', array('boardId' => $board->getId())))
            ->add($topic->getTitle(), $this->path('ccdn_forum_forum_topic_show', array('topicId' => $topic->getId())))
            ->add('#' . $post->getId(), $this->path('ccdn_forum_forum_post_show', array('postId' => $post->getId())));

        return $this->renderResponse('CCDNForumForumBundle:Post:show.html.', array(
            'crumbs' => $crumbs,
            'topic' => $topic,
            'post' => $post,
            'subscription' => $subscription,
            'subscription_count' => $subscriberCount,
        ));
    }

    /**
     *
     * @access public
     * @param  int                             $postId
     * @return RedirectResponse|RenderResponse
     */
    public function editAction($postId)
    {
        $this->isAuthorised('ROLE_USER');

        $user = $this->getUser();

        $post = $this->getPostModel()->findOneByIdWithTopicAndBoard($postId);
        $this->isFound($post);
        $this->isAuthorisedToViewPost($post);
        $this->isAuthorisedToEditPost($post);

        // If post is the very first post of the topic then use a topic handler so user can change topic title.
        if ($post->getTopic()->getFirstPost()->getId() == $post->getId()) {
            $formHandler = $this->getFormHandlerToEditTopic($post);
        } else {
            $formHandler = $this->getFormHandlerToEditPost($post);
        }

        if ($formHandler->process($this->getRequest())) {
            // get posts for determining the page of the edited post
            $topic = $post->getTopic();

            $page = $this->getModelManager()->getPageForPostOnTopic($topic, $post);

            $this->setFlash('success', $this->trans('flash.post.edit.success', array('%post_id%' => $postId, '%topic_title%' => $post->getTopic()->getTitle())));

            return $this->redirectResponse($this->path('ccdn_forum_forum_topic_show_paginated_anchored', array('topicId' => $topic->getId(), 'page' => $page, 'postId' => $post->getId() ) ));
        }

        // Setup crumb trail.
        $topic = $post->getTopic();
        $board = $topic->getBoard();
        $category = $board->getCategory();

        $crumbs = $this->getCrumbs()
            ->add($this->trans('crumbs.category.index'), $this->path('ccdn_forum_forum_category_index'))
            ->add($category->getName(),	$this->path('ccdn_forum_forum_category_show', array('categoryId' => $category->getId())))
            ->add($board->getName(), $this->path('ccdn_forum_forum_board_show', array('boardId' => $board->getId())))
            ->add($topic->getTitle(), $this->path('ccdn_forum_forum_topic_show', array('topicId' => $topic->getId())))
            ->add($this->trans('crumbs.post.edit') . $post->getId(), $this->path('ccdn_forum_forum_topic_reply', array('topicId' => $topic->getId())));

        if ($post->getTopic()->getFirstPost()->getId() == $post->getId()) {
            // render edit_topic if first post
            $template = 'CCDNForumForumBundle:Post:edit_topic.html.';
        } else {
            // render edit_post if reply post
            $template = 'CCDNForumForumBundle:Post:edit_post.html.';
        }

        return $this->renderResponse($template, array(
            'board' => $board,
            'topic' => $topic,
            'post' => $post,
            'crumbs' => $crumbs,
            'preview' => $formHandler->getForm()->getData(),
            'form' => $formHandler->getForm()->createView(),
        ));
    }

    /**
     *
     * @access public
     * @param  int                             $postId
     * @return RedirectResponse|RenderResponse
     */
    public function deleteAction($postId)
    {
        $this->isAuthorised('ROLE_USER');

        $post = $this->getPostModel()->findOneByIdWithTopicAndBoard($postId);
        $this->isFound($post);
        $this->isAuthorisedToViewPost($post);
        $this->isAuthorisedToDeletePost($post);

        $topic = $post->getTopic();
        $board = $topic->getBoard();
        $category = $board->getCategory();

        if ($post->getTopic()->getFirstPost()->getId() == $post->getId() && $post->getTopic()->getCachedReplyCount() == 0) {
            // if post is the very first post of the topic then use a topic handler so user can change topic title
            $confirmationMessage = 'ccdn_forum_forum.topic.delete_topic_question';
            $crumbDelete = $this->trans('ccdn_forum_forum.crumbs.topic.delete');
            $pageTitle = $this->trans('ccdn_forum_forum.title.topic.delete', array('%topic_title%' => $topic->getTitle()));
        } else {
            $confirmationMessage = 'ccdn_forum_forum.post.delete_post_question';
            $crumbDelete = $this->trans('ccdn_forum_forum.crumbs.post.delete') . $post->getId();
            $pageTitle = $this->trans('ccdn_forum_forum.title.post.delete', array('%post_id%' => $post->getId(), '%topic_title%' => $topic->getTitle()));
        }

        // setup crumb trail.
        $crumbs = $this->getCrumbs()
            ->add($this->trans('crumbs.category.index'), $this->path('ccdn_forum_forum_category_index'))
            ->add($category->getName(),	$this->path('ccdn_forum_forum_category_show', array('categoryId' => $category->getId())))
            ->add($board->getName(), $this->path('ccdn_forum_forum_board_show', array('boardId' => $board->getId())))
            ->add($topic->getTitle(), $this->path('ccdn_forum_forum_topic_show', array('topicId' => $topic->getId())))
            ->add($crumbDelete, $this->path('ccdn_forum_forum_topic_reply', array('topicId' => $topic->getId())));

        return $this->renderResponse('CCDNForumForumBundle:Post:delete_post.html.', array(
            'page_title' => $pageTitle,
            'confirmation_message' => $confirmationMessage,
            'topic' => $topic,
            'post' => $post,
            'crumbs' => $crumbs,
        ));
    }

    /**
     *
     * @access public
     * @param  int              $postId
     * @return RedirectResponse
     */
    public function deleteConfirmedAction($postId)
    {
        $this->isAuthorised('ROLE_USER');

        $post = $this->getPostModel()->findOneByIdWithTopicAndBoard($postId);
        $this->isFound($post);
        $this->isAuthorisedToViewPost($post);
        $this->isAuthorisedToDeletePost($post);

        $this->getPostModel()->softDelete($post, $this->getUser())->flush();

        // set flash message
        $this->setFlash('notice', $this->trans('flash.post.success.delete', array('%post_id%' => $postId)));

        return $this->redirectResponse($this->path('ccdn_forum_forum_topic_show', array('topicId' => $post->getTopic()->getId()) ));
    }
}

Resources/views/User/Post/Partial/body_content.html.twig
{%- spaceless -%}
{% if requested is defined %}
{% set body_content = post.getBody %}
{% set requested = requested|split(' ') %}
{% for requested1 in requested %}
	{% set body_content = body_content|replace({(requested1): ("<span style='color: yellow; background-color: red;'>" ~ requested1 ~ "</span>"),(requested1|lower): ("<span style='color: yellow; background-color: red;'>" ~ requested1 ~ "</span>")})|raw %}
	{% endfor %}
	{{ body_content|raw }}
{% else %}
	{{- post.getBody|raw -}}
{% endif %}

{%- endspaceless -%}

Resources/views/User/Post/Partial/item_post.html.twig
{%- spaceless -%}

	{%- macro class(post, topic) -%}

		{%- if post.isDeleted == true -%}
			panel-danger
		{%- else -%}
			{%- if post.id and post.topic -%}
				{%- if post.topic.firstPost -%}
					{%- if post.topic.firstPost.id == post.id -%}
						panel-primary
					{%- else -%}
						panel-default
					{%- endif -%}
				{%- else -%}
					panel-default
				{%- endif -%}
			{%- else -%}
				panel-default
			{%- endif -%}
		{% endif %}

	{%- endmacro -%}

	{%- import _self as post_panel -%}
	{%- set panel = post_panel.class(post, post.topic) -%}

	{%- if post.isDeleted == false or is_granted('ROLE_MODERATOR') -%}
	<div class="media">
		{%- include 'CCDNForumForumBundle:User:Post/Partial/item_post_head.html.twig' with {'post': post } -%}
		{%- include 'CCDNForumForumBundle:User:Post/Partial/item_post_body.html.twig' with {'post': post } -%}
	</div>
{% endif %}


{%- endspaceless -%}

Resources/views/User/Post/Partial/item_post_body.html.twig
{%- spaceless -%}

	{%- if post.isDeleted == false or is_granted('ROLE_MODERATOR') -%}
		{%- if post.getEditedDate -%}
        <div class="media-body">
			<div class="ibox-content">
					<i class="glyphicon glyphicon-pencil"></i>
					{{- 'post.edited-by' |trans({}, 'CCDNForumForumBundle') |raw -}}
					{{- post.getEditedBy.name -}}
					&nbsp;&#183;
					<abbr class="timestamper" title="{{- post.getEditedDate |date('Y-m-d H:i:s T Z', 'Europe/London') -}}">
						{{- post.getEditedDate |date(ccdn_forum_forum.item_post.edited_datetime_format) -}}
					</abbr>
				</div>
			</div>

		{%- endif -%}
	{%- endif -%}

	{%- if post.isDeleted == true -%}
		{%- if is_granted('ROLE_MODERATOR') -%}
            <div class="media-body">
				<div class="ibox-content">
					<i class="fa fa-fw fa-trash"></i>&nbsp;
					{{- 'post.deleted-by' |trans({}, 'CCDNForumForumBundle') |raw -}}
					{{- post.getDeletedBy.name -}}
					&nbsp;&#183;
					<abbr class="timestamper" title="{{- post.getDeletedDate |date('Y-m-d H:i:s T Z', 'Europe/London') -}}">
						{{- post.getDeletedDate |date(ccdn_forum_forum.item_post.deleted_datetime_format) -}}
					</abbr>
                    <br>
                    {{- post.getBody -}}
				</div>
             </div>
			{%- endif -%}

		{%- if is_granted('ROLE_MODERATOR') -%}
			<section class="accordion-body collapse" id="post_{{- post.getId() -}}_body">
				{%- include 'CCDNForumForumBundle:User:Post/Partial/body_content.html.twig' with {'post': post } -%}
			</section>
		{%- endif -%}
	{%- else -%}
		<div class="media-body">
			{%- include 'CCDNForumForumBundle:User:Post/Partial/body_content.html.twig' with {'post': post } -%}
        </div>


	{%- endif -%}



{%- endspaceless -%}

Resources/views/User/Post/Partial/item_post_head.html.twig
{%- spaceless -%}
	<a name="{{ post.id }}" id="{{ post.id }}"></a>

	{%- if post.isDeleted == false or is_granted('ROLE_MODERATOR') -%}
	<a class="forum-avatar" href="#">
	     <img class="img-thumbnail" src="{{ asset(profilepicture.getAvatarPath(post.getCreatedBy)) }}" style="max-width: none; width: 96px; height: 96px; !important;">
			<div class="author-info">
			<strong>Name: </strong> {{- post.getCreatedBy.name -}}<br>
			<strong>Posted: </strong> {{- post.getCreatedDate |date('d.m.Y H:i:s') -}} <br>
		</div>
	</a>


	    <div class="col-md-5 pull-right text-right">


            {%- if is_granted('ROLE_USER') and post.id and (is_granted('ROLE_MODERATOR') or not post.isDeleted) -%}
				&nbsp;
                <div class="dropdown btn-group text-left">
                    <a class="dropdown-toggle btn btn-xs btn-icon-only" data-toggle="dropdown" href="#">
						<i class="glyphicon glyphicon-cog"></i>
						<span class="caret"></span>
					</a>
                    <ul class="dropdown-menu pull-right content-left" >

						{%- if canReplyToTopic(post.getTopic) -%}
	                        <li>
								<a rel="nofollow"
								 href="{{- path('ccdn_forum_user_topic_reply', {'forumName': forumName, 'topicId': post.getTopic.getId }) -}}">
									<i class="glyphicon glyphicon-pencil"></i>
									{{- 'link.topic.reply' | trans({}, 'CCDNForumForumBundle') -}}
								</a>
							</li>
						{%- endif -%}

						{%- if canEditPost(post) -%}
                            <li>
								<a rel="nofollow" id="post_edit[{{- post.getBody |slice(0,24) -}}]"
								 href="{{- path('ccdn_forum_user_post_edit', {'forumName': forumName, 'postId': post.getId }) -}}">
									<i class="glyphicon glyphicon-pencil"></i>
									{{- 'link.edit' | trans({}, 'CCDNForumForumBundle') -}}
								</a>
							</li>
						{%- endif -%}

                        {%- if canDeletePost(post) -%}
                            <li>
								<a rel="nofollow"
								 href="{{- path('ccdn_forum_user_post_delete', {'forumName': forumName, 'postId': post.getId }) -}}">
									<i class="glyphicon glyphicon-trash"></i>
									{{- 'link.post.delete' | trans({}, 'CCDNForumForumBundle') -}}
								</a>
							</li>
                        {%- endif -%}

						{%- if canRestorePost(post) -%}
                            <li>
                                <a rel="nofollow" href="{{- path('ccdn_forum_moderator_post_restore', {'forumName': forumName, 'postId': post.getId }) -}}">
                                    <i class="glyphicon glyphicon-trash"></i>
									{{- 'link.post.restore' | trans({}, 'CCDNForumForumBundle') -}}
                                </a>
                            </li>
                        {%- endif -%}

						{%- if canLockPost(post) -%}
                            <li>
                                <a rel="nofollow" href="{{- path('ccdn_forum_moderator_post_lock', {'forumName': forumName, 'postId': post.getId }) -}}">
                                    <i class="glyphicon glyphicon-lock"></i>
									{{- 'link.post.lock' | trans({}, 'CCDNForumForumBundle') -}}
                                </a>
                            </li>
						{%- endif -%}

						{%- if canUnlockPost(post) -%}
                            <li>
                                <a rel="nofollow" href="{{- path('ccdn_forum_moderator_post_unlock', {'forumName': forumName, 'postId': post.getId }) -}}">
                                    <i class="glyphicon glyphicon-lock"></i>
									{{- 'link.post.unlock' | trans({}, 'CCDNForumForumBundle') -}}
                                </a>
                            </li>
                        {%- endif -%}

                    </ul>
                </div>
            {%- endif -%}
		</div>
{% endif %}

{%- endspaceless -%}

Resources/views/User/Post/Partial/post_preview.html.twig
{%- spaceless -%}
    {%- if preview.getBody -%}
<div class="forum-topic-transcript">
	<div class="ibox">
		<div class="ibox-title">
			<h5>{{- 'post.preview' |trans({}, 'CCDNForumForumBundle') -}}</h5>

			<div class="ibox-tools">
				<a class="collapse-link">
					<i class="fa fa-fw fa-chevron-up"></i>
				</a>
				<a class="close-link">
					<i class="fa fa-fw fa-times"></i>
				</a>
			</div>
		</div>
		<div class="ibox-content">
			<div style="position: relative; overflow: hidden; width: auto; height: auto;" class="slimScrollDiv">
				<div style="overflow: hidden; width: auto; height: auto;" class="scroll_content">

			    <div class="media">
					<h4 class="media-heading">
						{%- if post.getCreatedBy -%}
					        {{- 'post.posted-by' |trans({}, 'CCDNForumForumBundle') |raw -}}
							{{- post.getCreatedBy.username -}}

					        &nbsp;&#183;&nbsp;

						{%- endif -%}

				        <span class="timestamper" title="{{- post.getCreatedDate |date('d.m.Y H:i:s T Z', 'Europe/London') -}}">
				           {{- post.getCreatedDate |date('d.m.Y H:i:s') -}}
				        </span>
					</h4>
				</div>

				<div class="media">
                    {{ post.getBody|raw }}
				</div>

			</div>
		</div>
         </div>
        </div>
    </div>

            {%- endif -%}
{%- endspaceless -%}